name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: tradepackage/tradebot

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: /bin/bash /startdomain
